DASH_APPLICATION = "dash-application"
NAVBAR_COLLAPSE = "navbar-collapse"
NAVBAR_TOGGLER = "navbar-toggler"

# Charts
ANNUAL_RETURNS_BAR_CHART = "annual-returns-bar-chart"
PERF_STATS_TABLE = "perf-stats-table"
TOP_DRAWDOWN_TABLE = "top-drawdown-table"
RETURNS_CHART = "returns-chart"
CUMULATIVE_RETURNS_CHART = "cumulative-returns-chart"
CUMULATIVE_RETURNS_LOG_SCALE_CHART = "cumulative-returns-log-scale-chart"
CUMULATIVE_RETURNS_VOL_MATCH_BMK_CHART = "cumulative-returns-vol-match-bmk-chart"
DRAWDOWN_RETURNS_CHART = "drawdown-returns-chart"
MONTHLY_RETURNS_HEATMAP = "monthly-returns-heatmap"
ROLLING_VOLATILITY_CHART = "rolling-volatility-chart"
ROLLING_SHARPE_RATIO_CHART = "rolling-sharpe-ratio"
ROLLING_BETA_CHART = "rolling-beta-ratio"
MONNTLY_RETURNS_DIST = "monthly-returns-dist"
RETURNS_QUANTILES_PLOT = "returns-quantiles-plot"
